stages:
  - build

build_linux_x64:
  stage: build
  image: registry.lanni/nibuntu/sdk-20.04:latest
  script:
    - make
  artifacts:
    untracked: false
    paths:
      - linux/*.so*

build_vs2022_windows:
  stage: build
  image: registry.lanni/microsoft/win10-vc-build-tools-2022:latest
  script:
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Debug -p:Platform=x64
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Release -p:Platform=Win32
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Debug -p:Platform=Win32
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x64"
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x64d"
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x86"
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x86d"
  tags:
    - docker-windows
  artifacts:
    untracked: false
    paths:
      - dist/x64/*.dll
      - dist/x64d/*.dll
      - dist/x86/*.dll
      - dist/x86d/*.dll
      - dist/x64/*.lib
      - dist/x64d/*.lib
      - dist/x86/*.lib
      - dist/x86d/*.lib
      - dist/x64/*.h
      - dist/x64d/*.h
      - dist/x86/*.h
      - dist/x86d/*.h      

# build_vs2022_windows_x86:
#   stage: build
#   image: registry.lanni/microsoft/win10-vc-build-tools-2022:latest
#   script:
#     - MSBuild cpp-sample_2022.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86
#   tags:
#     - docker-windows
#   artifacts:
#     untracked: false
#     paths:
#       - dist/x86/*.dll

# build_vs2017_windows_x64:
#   stage: build
#   image: registry.lanni/microsoft/win10-vc-build-tools-2017:latest
#   script:
#     - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
#   tags:
#     - docker-windows
#   artifacts:
#     untracked: false
#     paths:
#       - dist/x64/*.dll

# build_vs2017_windows_x86:
#   stage: build
#   image: registry.lanni/microsoft/win10-vc-build-tools-2017:latest
#   script:
#     - MSBuild cpp-sample_2017.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86
#   tags:
#     - docker-windows
#   artifacts:
#     untracked: false
#     expire_in: "30 days"
#     paths:
#       - Release/cpp-sample_2017.exe
