stages:
  - build
  - release

build_vs2022_windows:
  stage: build
  image: registry.lanni/microsoft/win10-vc-build-tools-2022:latest
  script:
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Debug -p:Platform=x64
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Release -p:Platform=Win32
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Debug -p:Platform=Win32
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x64"
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x64d"
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x86"
    - Copy-Item ".\R5560_SDKLib\R5560_SDKLib.h" -Destination "dist\x86d"
  tags:
    - docker-windows
  artifacts:
    untracked: false
    name: windows
    paths:
      - dist/x64/*.dll
      - dist/x64d/*.dll
      - dist/x86/*.dll
      - dist/x86d/*.dll
      - dist/x64/*.lib
      - dist/x64d/*.lib
      - dist/x86/*.lib
      - dist/x86d/*.lib
      - dist/x64/*.h
      - dist/x64d/*.h
      - dist/x86/*.h
      - dist/x86d/*.h     
    expire_in: 1 week 
  rules:
    - if: $CI_COMMIT_TAG

build_all_arch:
  stage: build
  image: registry.lanni/nibuntu/build-20.04
  script:
    - apt update
    - apt install -y libzmq3-dev
    - apt install -y libzmq3-dev:i386
    - apt install -y libzmq3-dev:arm64
    - apt install -y libzmq3-dev:armhf
    - compile_all_architecures.sh
    #- build_debs.sh
  artifacts:
    untracked: false
    paths:
      - build_x64/output/*
      - build_i386/output/*
      - build_arm64/output/*
      - build_armhf/output/*
      - ./*.deb

build_zynq:
  stage: build
  image: registry.lanni/nibuntu/console-20.04:latest
  script:
    - ./compile_for_zynq.sh
  artifacts:
    untracked: false
    paths:
      - build_zynq/libr5560-zynq.tar.gz

build_all_arch_focal:
  stage: build
  image: registry.lanni/nibuntu/build-20.04:latest
  variables:
    LINUXRELEASE: "focal"
  script:
    - echo $CI_COMMIT_TAG>VERSION
    - ./compile_all_architecures.sh
    - ./compile_deb.sh
    - mkdir tars
    - mkdir debs
    - mv libr5560-x64.deb debs/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-x64.deb
    - mv libr5560-i386.deb debs/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-i386.deb
    - mv libr5560-arm64.deb debs/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-arm64.deb
    - mv libr5560-armhf.deb debs/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-armhf.deb
    - mv libr5560-x64.tar.gz tars/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-x64.tar.gz
    - mv libr5560-i386.tar.gz tars/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-i386.tar.gz
    - mv libr5560-arm64.tar.gz tars/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-arm64.tar.gz
    - mv libr5560-armhf.tar.gz tars/libr5560-$CI_COMMIT_TAG-$LINUXRELEASE-armhf.tar.gz
    - cd tars
    - tar zcvf ../libr5560-lib-$LINUXRELEASE.tar.gz .
    - cd ../debs
    - tar zcvf ../libr5560-deb-$LINUXRELEASE.tar.gz .

  artifacts:
    untracked: false
    paths:
    - libr5560-lib-$LINUXRELEASE.tar.gz
    - libr5560-deb-$LINUXRELEASE.tar.gz

  rules:
    - if: $CI_COMMIT_TAG

nirelease:
  stage: release
  image: registry.lanni/apps/release-manager:latest
  dependencies: 
    - build_vs2022_windows
    - build_zynq  
    - build_all_arch_focal
  script:
    - mv dist windows
    - zip -r windows_x86_x64.zip windows
    - nirelease -f ni-release-windows.yaml -c -v $CI_COMMIT_TAG -m "Autogenerated by pipeline with tag $CI_COMMIT_TAG"
    - nirelease -f ni-release-zynq.yaml -c -v $CI_COMMIT_TAG -m "Autogenerated by pipeline with tag $CI_COMMIT_TAG"
    - nirelease -f ni-release-linux.yaml -c -v $CI_COMMIT_TAG -m "Autogenerated by pipeline with tag $CI_COMMIT_TAG"
    - echo "Generate diff from last release for the latest release"
    - if [ -f CHANGELOG.md ]; then LATEST_TAG=`git tag --sort=-creatordate | head -2 | tail -n 1`; fi
    - if [ -f CHANGELOG.md ]; then git diff $LATEST_TAG ./CHANGELOG.md | tail -n +6 | sed -n "/^+/p" | sed -e "s/^+//" > ./latestChanges.md; fi
    - if [ ! -f CHANGELOG.md ]; then touch latestChanges.md; fi
    - echo "Creating release with the following changelog changes:"
    - cat latestChanges.md    
    - export URLNR=$(nirelease -f ni-release-windows.yaml --geturl)
    - export URLNR2=$(nirelease -f ni-release-zynq.yaml --geturl)
    - export URLNR3=$(nirelease -f ni-release-linux.yaml --geturl)
    - release-cli create --description "./latestChanges.md" --tag-name "$CI_COMMIT_TAG" --assets-link "[{\"url\":\"$URLNR\",\"name\":\"r5560sdk-win-$CI_COMMIT_TAG\"}, {\"url\":\"$URLNR2\",\"name\":\"libr5560-zynq-$CI_COMMIT_TAG\"}, {\"url\":\"$URLNR3\",\"name\":\"libr5560-linux-$CI_COMMIT_TAG\"}]"
      

  rules:
    - if: $CI_COMMIT_TAG
  when: on_success



