stages:
  - build


build_all_arch:
  stage: build
  image: registry.lanni/nibuntu/build-20.04
  script:
    - apt update
    - apt install -y libzmq3-dev
    - apt install -y libzmq3-dev:i386
    - apt install -y libzmq3-dev:arm64
    - apt install -y libzmq3-dev:armhf
    - compile_all_architecures.sh
    - build_debs.sh
  artifacts:
    untracked: false
    paths:
      - build_x64/output/*
      - build_i386/output/*
      - build_arm64/output/*
      - build_armhf/output/*
      - ./*.deb
# build_vs2022_windows_x64:
#   stage: build
#   image: registry.lanni/microsoft/win10-vc-build-tools-2022:latest
#   script:
#     - MSBuild cpp-sample_2022.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
#   tags:
#     - docker-windows
#   artifacts:
#     untracked: false
#     expire_in: "30 days"
#     paths:
#       - x64/Release/cpp-sample_2022.exe

# build_vs2022_windows_x86:
#   stage: build
#   image: registry.lanni/microsoft/win10-vc-build-tools-2022:latest
#   script:
#     - MSBuild cpp-sample_2022.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86
#   tags:
#     - docker-windows
#   artifacts:
#     untracked: false
#     expire_in: "30 days"
#     paths:
#       - Release/cpp-sample_2022.exe

build_vs2017_windows_x64:
  stage: build
  image: registry.lanni/microsoft/win10-vc-build-tools-2017:latest
  script:
    - MSBuild R5560_SDKApp.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
  tags:
    - docker-windows
  artifacts:
    untracked: false
    paths:
      - dist/x64/*.dll

# build_vs2017_windows_x86:
#   stage: build
#   image: registry.lanni/microsoft/win10-vc-build-tools-2017:latest
#   script:
#     - MSBuild cpp-sample_2017.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86
#   tags:
#     - docker-windows
#   artifacts:
#     untracked: false
#     expire_in: "30 days"
#     paths:
#       - Release/cpp-sample_2017.exe
